[package]
name = "pve-rs"
version = "0.8.2"
description = "PVE parts which have been ported to Rust"
homepage = "https://www.proxmox.com"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2021"
license = "AGPL-3"
repository = "https://git.proxmox.com/?p=proxmox.git"

exclude = [
    "debian",
]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1.0"
base32 = "0.4"
base64 = "0.13"
env_logger = "0.9"
hex = "0.4"
http = "0.2.7"
libc = "0.2"
nix = "0.26"
openssl = "0.10.40"
serde = "1.0"
serde_bytes = "0.11"
serde_json = "1.0"
url = "2"

perlmod = { version = "0.13", features = [ "exporter" ], git = "https://git.proxmox.com/git/perlmod.git" }

proxmox-apt = { version = "0.10", git = "https://git.proxmox.com/git/proxmox.git" }
proxmox-http = { version = "0.9", features = ["client-sync", "client-trait"], git = "https://git.proxmox.com/git/proxmox.git" }
proxmox-openid = { version = "0.10", git = "https://git.proxmox.com/git/proxmox.git" }
proxmox-resource-scheduling = { version = "0.3.0", git = "https://git.proxmox.com/git/proxmox-resource-scheduling.git" }
proxmox-subscription = { version = "0.4", git = "https://git.proxmox.com/git/proxmox.git" }
proxmox-sys = { version = "0.5", git = "https://git.proxmox.com/git/proxmox.git" }
proxmox-tfa = { version = "4.0.2", features = ["api"], git = "https://git.proxmox.com/git/proxmox.git" }
proxmox-time = { version = "1.1.3", git = "https://git.proxmox.com/git/proxmox.git" }
